services:
  - type: web
    name: ultimate-api-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python run.py"
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production 